export enum PermissionEnum {
  CAN_READ_ROLES = 'CAN_READ_ROLES',
  CAN_CREATE_ROLES = 'CAN_CREATE_ROLES',
  CAN_EDIT_ROLES = 'CAN_EDIT_ROLES',
  CAN_DELETE_ROLES = 'CAN_DELETE_ROLES',

  CAN_READ_USERS = 'CAN_READ_USERS',
  CAN_EDIT_USERS = 'CAN_EDIT_USERS',
  CAN_DELETE_USERS = 'CAN_DELETE_USERS',
  CAN_CREATE_USERS = 'CAN_CREATE_USERS',
}
